const words=[
  ['apple','an apple','🍎','countable'],['banana','a banana','🍌','countable'],['egg','an egg','🥚','countable'],['cookie','a cookie','🍪','countable'],['carrot','a carrot','🥕','countable'],['orange','an orange','🍊','countable'],['sandwich','a sandwich','🥪','countable'],['strawberry','a strawberry','🍓','countable'],['tomato','a tomato','🍅','countable'],['potato','a potato','🥔','countable'],['lemon','a lemon','🍋','countable'],['grape','a grape','🍇','countable'],
  ['milk','some milk','🥛','uncountable'],['water','some water','💧','uncountable'],['rice','some rice','🍚','uncountable'],['bread','some bread','🍞','uncountable'],['cheese','some cheese','🧀','uncountable'],['butter','some butter','🧈','uncountable'],['coffee','some coffee','☕','uncountable'],['tea','some tea','🍵','uncountable'],['soup','some soup','🥣','uncountable'],['honey','some honey','🍯','uncountable'],['juice','some juice','🧃','uncountable'],['pasta','some pasta','🍝','uncountable']
].map(([en,example,emoji,type])=>({en,example,emoji,type}));
const grid=document.querySelector('#vocab-grid');
function speak(word){if(!('speechSynthesis'in window))return; speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(word);u.lang='en-US';u.rate=.82;speechSynthesis.speak(u)}
function renderWords(filter='all'){grid.innerHTML='';words.filter(w=>filter==='all'||w.type===filter).forEach(w=>{const b=document.createElement('button');b.className='vocab-card';b.type='button';b.setAttribute('aria-label',`${w.en}, ${w.example}. Play pronunciation`);b.innerHTML=`<div class="vocab-visual" aria-hidden="true">${w.emoji}</div><div class="vocab-info"><strong>${w.en} 🔊</strong><small>${w.example}</small><span class="vocab-type ${w.type}">${w.type==='countable'?'COUNTABLE':'NON-COUNTABLE'}</span></div>`;b.addEventListener('click',()=>speak(w.en));grid.appendChild(b)})}
document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(x=>{x.classList.remove('active');x.setAttribute('aria-pressed','false')});b.classList.add('active');b.setAttribute('aria-pressed','true');renderWords(b.dataset.filter)}));renderWords();
const content=document.querySelector('#game-content');let activeGame='cards',sortIndex=0,sortScore=0,choiceIndex=0,choiceScore=0,memoryFlipped=[],memoryMatched=0,memoryLocked=false,cardDeck=[...words],cardIndex=0,cardFlipped=false;
const sortDeck=[words[0],words[12],words[2],words[14],words[4],words[16],words[7],words[19],words[10],words[22]];
const choiceDeck=[{emoji:'🍎 🍎 🍎',q:'Choose the best phrase',options:['many apples','much apples','a little apples','a slice of apples'],answer:0},{emoji:'🥛',q:'Choose the best phrase',options:['a few milk','a little milk','many milk','an milk'],answer:1},{emoji:'🍌 🍌',q:'Choose the best phrase',options:['a little bananas','much bananas','a few bananas','a slice of bananas'],answer:2},{emoji:'🍞',q:'Choose the best phrase',options:['a slice of bread','a few bread','many bread','an bread'],answer:0},{emoji:'🧀',q:'Choose the best phrase',options:['a few cheese','many cheese','some cheese','an cheese'],answer:2},{emoji:'🥚 🥚 🥚',q:'Choose the best phrase',options:['much eggs','a little eggs','many eggs','a slice of eggs'],answer:2}];
function setGame(game){activeGame=game;const shell=document.querySelector('.game-shell');document.querySelectorAll('.game-tab').forEach(b=>{const on=b.dataset.game===game;b.classList.toggle('active',on);b.setAttribute('aria-expanded',String(on));b.querySelector('.tab-arrow').textContent=on?'⌃':'⌄';if(on)b.after(shell)});if(game==='cards')renderCards();if(game==='sort')renderSort();if(game==='memory')renderMemory();if(game==='choose')renderChoose()}
document.querySelectorAll('.game-tab').forEach(b=>b.addEventListener('click',()=>setGame(b.dataset.game)));
function header(title,help,score){return `<div class="game-header"><div><h3>${title}</h3><p>${help}</p></div><div class="score">★ ${score}</div></div>`}
function renderCards(){let w=cardDeck[cardIndex];content.innerHTML=header('Flashcard deck','Look at the picture, flip the card, and hear the word.',`${cardIndex+1}/${cardDeck.length}`)+`<button class="flashcard" id="flashcard" aria-label="${cardFlipped?'Show picture':'Show word'}"><span class="flashcard-emoji" aria-hidden="true">${w.emoji}</span><span class="flashcard-word">${cardFlipped?w.en:'What is this in English?'}</span><span class="flashcard-meaning">${cardFlipped?w.example:'Tap to reveal'}</span></button><div class="card-controls"><button class="game-choice" id="card-prev" ${cardIndex===0?'disabled':''}>← Previous</button><button class="game-choice" id="card-flip">Flip ↻</button><button class="game-choice" id="card-audio">Listen 🔊</button><button class="game-choice" id="card-next" ${cardIndex===cardDeck.length-1?'disabled':''}>Next →</button></div><div class="card-extras"><button class="reset-button" id="card-shuffle">Shuffle</button><button class="reset-button" id="card-reset">Original order</button></div>`;const flip=()=>{cardFlipped=!cardFlipped;renderCards()};content.querySelector('#flashcard').onclick=flip;content.querySelector('#card-flip').onclick=flip;content.querySelector('#card-prev').onclick=()=>{cardIndex--;cardFlipped=false;renderCards()};content.querySelector('#card-next').onclick=()=>{cardIndex++;cardFlipped=false;renderCards()};content.querySelector('#card-audio').onclick=()=>speak(w.en);content.querySelector('#card-shuffle').onclick=()=>{cardDeck=[...words].sort(()=>Math.random()-.5);cardIndex=0;cardFlipped=false;renderCards()};content.querySelector('#card-reset').onclick=()=>{cardDeck=[...words];cardIndex=0;cardFlipped=false;renderCards()}}
function renderSort(){if(sortIndex>=sortDeck.length){content.innerHTML=header('Well done!','You sorted every word.',`${sortScore}/${sortDeck.length}`)+`<button class="button button-primary" id="sort-reset">Play again ↻</button>`;document.querySelector('#sort-reset').onclick=()=>{sortIndex=0;sortScore=0;renderSort()};return}let w=sortDeck[sortIndex];content.innerHTML=header('Food sort','Look at the picture and choose its group.',`${sortScore}/${sortDeck.length}`)+`<div class="sort-prompt" aria-hidden="true">${w.emoji}</div><div class="sort-word">${w.en}</div><div class="sort-options"><button class="game-choice" data-answer="countable">🔵 Countable</button><button class="game-choice" data-answer="uncountable">🟠 Non-countable</button></div><div class="game-feedback" aria-live="polite"></div>`;content.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{let good=b.dataset.answer===w.type;if(good)sortScore++;const f=content.querySelector('.game-feedback');f.textContent=good?'Correct! ✳':'Not quite. It is '+(w.type==='countable'?'Countable':'Non-countable')+'.';f.className='game-feedback '+(good?'good':'bad');content.querySelectorAll('[data-answer]').forEach(x=>x.disabled=true);setTimeout(()=>{sortIndex++;if(activeGame==='sort')renderSort()},900)})}
function renderMemory(){const pairs=[words[0],words[1],words[12],words[14],words[16],words[17]];let deck=pairs.flatMap((w,i)=>[{id:i,value:w.emoji,kind:'image'},{id:i,value:w.en,kind:'word'}]).sort(()=>Math.random()-.5);memoryFlipped=[];memoryMatched=0;memoryLocked=false;content.innerHTML=header('Memory match','Match each picture with its word.',`0/${pairs.length}`)+`<div class="memory-grid"></div><button class="reset-button" id="memory-reset">Shuffle again ↻</button><div class="game-feedback" aria-live="polite"></div>`;const board=content.querySelector('.memory-grid');deck.forEach((card,i)=>{let b=document.createElement('button');b.className='memory-card';b.type='button';b.setAttribute('aria-label','Hidden card');b.innerHTML='<span class="back">✳</span>';b.onclick=()=>{if(memoryLocked||b.classList.contains('flipped')||b.classList.contains('matched'))return;b.classList.add('flipped');b.innerHTML=`<span class="${card.kind==='word'?'word':''}">${card.value}</span>`;b.setAttribute('aria-label',card.value);memoryFlipped.push({button:b,card});if(memoryFlipped.length===2){let [a,c]=memoryFlipped;memoryLocked=true;if(a.card.id===c.card.id){a.button.classList.add('matched');c.button.classList.add('matched');memoryMatched++;content.querySelector('.score').textContent=`★ ${memoryMatched}/${pairs.length}`;content.querySelector('.game-feedback').textContent=memoryMatched===pairs.length?'You found every pair! 🎉':'Good job!';memoryFlipped=[];memoryLocked=false}else{setTimeout(()=>{[a,c].forEach(x=>{x.button.classList.remove('flipped');x.button.innerHTML='<span class="back">✳</span>';x.button.setAttribute('aria-label','Hidden card')});memoryFlipped=[];memoryLocked=false},850)}}};board.appendChild(b)});content.querySelector('#memory-reset').onclick=renderMemory}
function renderChoose(){if(choiceIndex>=choiceDeck.length){content.innerHTML=header('Excellent!','You completed the quantity challenge.',`${choiceScore}/${choiceDeck.length}`)+`<button class="button button-primary" id="choice-reset">Play again ↻</button>`;content.querySelector('#choice-reset').onclick=()=>{choiceIndex=0;choiceScore=0;renderChoose()};return}let c=choiceDeck[choiceIndex];content.innerHTML=header('Picture challenge','Look at the picture and choose the phrase.',`${choiceScore}/${choiceDeck.length}`)+`<div class="choice-picture" aria-hidden="true">${c.emoji}</div><div class="choice-question">${c.q}</div><div class="choice-options">${c.options.map((o,i)=>`<button class="game-choice" data-choice="${i}">${o}</button>`).join('')}</div><div class="game-feedback" aria-live="polite"></div>`;content.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{let good=Number(b.dataset.choice)===c.answer;if(good)choiceScore++;let f=content.querySelector('.game-feedback');f.textContent=good?'Yes, that is it! ✳':'The phrase is: '+c.options[c.answer];f.className='game-feedback '+(good?'good':'bad');content.querySelectorAll('[data-choice]').forEach(x=>x.disabled=true);setTimeout(()=>{choiceIndex++;if(activeGame==='choose')renderChoose()},1100)})}
setGame('cards');
const prompts=[['some rice','a few carrots','a little juice'],['a slice of bread','some cheese','a few grapes'],['a few eggs','some pasta','a little water'],['many strawberries','some milk','a little honey'],['some bread','a few tomatoes','a little tea']];let promptIndex=-1;document.querySelector('#new-prompt').addEventListener('click',()=>{promptIndex=(promptIndex+1)%prompts.length;document.querySelector('#challenge-prompt').textContent='Try: '+prompts[promptIndex].join(' · ')});

